metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# System metrics
metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
  enabled: true
  period: 10s
  processes: ['.*']

- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

# HTTP metrics for monitoring microservices endpoints
- module: http
  metricsets:
    - json
  period: 30s
  hosts:
    - "http://api-gateway-container:8080/actuator/health"
    - "http://user-service-container:8700/actuator/health"
    - "http://product-service-container:8500/actuator/health"
    - "http://order-service-container:8300/actuator/health"
    - "http://payment-service-container:8400/actuator/health"
    - "http://shipping-service-container:8600/actuator/health"
  namespace: "health"
  path: "/"

# JVM metrics for Spring Boot applications
- module: jolokia
  metricsets: ["jmx"]
  period: 10s
  namespace: "metrics"
  hosts:
    - "api-gateway-container:8080"
    - "user-service-container:8700"
    - "product-service-container:8500"
    - "order-service-container:8300"
    - "payment-service-container:8400"
    - "shipping-service-container:8600"
  path: "/actuator/jolokia"
  jmx.mappings:
    - mbean: 'java.lang:type=Runtime'
      attributes:
        - attr: Uptime
          field: uptime
    - mbean: 'java.lang:type=Memory'
      attributes:
        - attr: HeapMemoryUsage
          field: heap

# Add processors
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~

# Output to Elasticsearch
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  template.name: "metricbeat"
  template.pattern: "metricbeat-*"
  template.settings:
    index.number_of_shards: 1
    index.codec: best_compression

# Kibana configuration
setup.kibana:
  host: "kibana:5601"

# Logging
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat
  keepfiles: 7
  permissions: 0644